#include <stdio.h>
#include <pthread.h>
#include <unistd.h> 
#include <stdint.h>  
#include <stdlib.h>
#include <string.h>    
#include <unistd.h> 
#include <sys/reboot.h>
#include <malloc.h>   
#include <sys/types.h>   
#include <sys/stat.h>     
#include <fcntl.h> 
#include <float.h>    
#include <termios.h>  
#include <errno.h>       
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/ip.h>
#include <net/if.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <string.h>
#include <sys/select.h>
#include <sys/time.h>
#include <sys/mman.h>
#include <sys/ioctl.h>
#include <time.h>
#include <signal.h>
#include <math.h>
#include "usart.h"
#include "client.h"
#include "mypthread.h"
#include "main.h"
#include <limits.h>
#include <ctype.h>
#include "cjson.h"
#include "cjson_check.h"
#include "s_func.h"

